### ISSUE TITLE
Subscription - syntax error, unexpected 'array'

### ISSUE THREAD

**Issue by richard-313** [hypnodev/larapal#1]
hi, thanks for this awesome package and work!
If I call 
```
$user = Auth::user();
$user->subscribeWithPaypal('My custom plan id');
```
I get the following error:

**syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)**

My test development ist laravel 6.

thanks for help :)

**Comment by hypnodev** [comment]
Hi!
Can you tell me which version of PHP you're using?

**Comment by richard-313** [comment]
PHP 7.3.11

**Comment by hypnodev** [comment]
Please upgrade your php version to 7.4

**Comment by hypnodev** [comment]
Closed due to inactivity.
